##########################///Instrução para o deploy manual - ONE CLICK STACKS\\\###############################
#                        para implantação manual baixe ou copie esse arquivo                                   #
#                                   comando para o deploy manual                                               #
#                DOMAIN=traefik.seudominio.com docker stack deploy -c traefik.yml traefik                      #
#                          Nunca faça deploy sem a variavel ACME_EMAIL declarada                               #
#     Variavleis podem ser editadas em App templates >> Copy as Custom ou no serviço após ser implantado       #
################################################################################################################

version: '3.8'

services:
  traefik:
    image: traefik:${VERSION:-v2.9.5}
    command:
      # - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.network=traefik-public
      - --providers.docker.exposedByDefault=false
      - --providers.docker.swarmMode=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entryPoints.http.proxyProtocol.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entryPoints.http.forwardedHeaders.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entryPoints.https.proxyProtocol.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entryPoints.https.forwardedHeaders.trustedIPs=${TRUSTED_IPS:-127.0.0.1}
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    volumes:
      - ${VOLUME_PATH}letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - {target: 80, published: 80, mode: host, protocol: tcp}
      - {target: 443, published: 443, mode: host, protocol: tcp}
    deploy:
      mode: ${MODE:-replicated}

volumes:
  letsencrypt:

networks:
  default:
    external: true
    name: traefik-public
